// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "./Button.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

import './App.css'
;

function App(props) {
  let match = React.useState(() => 0);
  let setCount = match[1];
  let button_text = "count is " + match[0].toString();
  let countAction = param => setCount(count => count + 1 | 0);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "What is this about?"
      }),
      JsxRuntime.jsx("p", {
        children: "This is a simple template for a Vite project using ReScript & Tailwind CSS."
      }),
      JsxRuntime.jsx("h2", {
        children: "Fast Refresh Test"
      }),
      JsxRuntime.jsx(Button.make, {
        children: button_text,
        onClick: countAction
      }),
      JsxRuntime.jsxs("p", {
        children: [
          "Edit ",
          JsxRuntime.jsx("code", {
            children: "src/App.res"
          }),
          " and save to test Fast Refresh."
        ]
      })
    ]
  });
}

let make = App;

export {
  make,
}
/*  Not a pure module */
