// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function make(props) {
  return JsxRuntime.jsx("button", props);
}

export {
  make,
}
/* react/jsx-runtime Not a pure module */
